Fonts folder and classes
jocke1995/StortSpelProjekt pull request #10
Opened 2020-09-08 12:57 UTC by fredrix96

A new resource folder has been added called Fonts. This folder is supposed to host all the different fonts we want to use in the game. 
A new class called Text has been added to Renderer, where some necessary structs have been declared. 
A TextTask class and two new shaders called TextVertex and TextPixel have also been added.

2020-09-08 14:56 UTC, Schtekt reviewed
Missing an inclusion of "stdafx.h" in Text.cpp. Looks good otherwise.

2020-09-09 06:57 UTC, jakkeez requested changes
Missing an inclusion of "stdafx.h" in Text.cpp. Looks good otherwise. // Tim

2020-09-11 11:06 UTC, jakkeez approved these changes

2020-09-11 11:06 UTC, Schtekt approved these changes

2020-09-11 11:07 UTC, merged