Player Data on server and some more
jocke1995/StortSpelProjekt pull request #113
Opened 2020-10-13 14:06 UTC by Anteanten

This show player entities also turning and that their info is stored on server

This include some things conserning enemies and host. This is for another task i've been accidently working on

2020-10-13 15:08 UTC, OtakuFreak13 submitted a review, later dismissed
Test scene runs and so does Game. Code seems fine.

2020-10-14 08:25 UTC, OtakuFreak13 submitted a review, later dismissed

2020-10-14 14:47 UTC, Whixx requested changes
Codestandard comment

2020-10-14 14:47 UTC, Whixx commented on StortSpelProjekt/Server/src/ClientPool.h
> +	ServerGame* m_State;
pointer, m_pState...?

2020-10-14 14:50 UTC, OtakuFreak13 submitted a review, later dismissed

2020-10-14 14:54 UTC, Whixx approved these changes

2020-10-14 14:54 UTC, OtakuFreak13 approved these changes

2020-10-14 14:54 UTC, merged