Audio library
jocke1995/StortSpelProjekt pull request #13
Opened 2020-09-09 10:19 UTC by kattalainen

Added audio engine and audio class and testing in sandbox main

2020-09-09 12:04 UTC, LeoWikstrom requested changes

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +{
Minne från medlemsvariabler som är pekare måste frigöras

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +        return HRESULT_FROM_WIN32(GetLastError());
If-satser ska skrivas i block, enligt vår kodstandard, ex:
if (true)
{
   doSomething();
}

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +            hr = HRESULT_FROM_WIN32(GetLastError());
If-sats i block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +            hr = HRESULT_FROM_WIN32(GetLastError());
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +                hr = HRESULT_FROM_WIN32(GetLastError());
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +                return HRESULT_FROM_WIN32(GetLastError());
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +        if (bytesRead >= dwRIFFDataSize) return S_FALSE;
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +        return HRESULT_FROM_WIN32(GetLastError());
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +        hr = HRESULT_FROM_WIN32(GetLastError());
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +        Log::Print("Invalid handle value\n");
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.cpp
> +        Log::Print("Invalid set file pointer\n");
Block

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.h
> +	IXAudio2SourceVoice* pSourceVoice;
Borde heta m_pSourceVoice, enligt vår kodstandard

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/AudioEngine.cpp
> +	//Log::Print("CREATED SOME SHET\n");
Städa gärna undan gamla kommentarer

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/AudioEngine/AudioEngine.cpp
> +{
Måste frigöra minne från pekare

2020-09-09 12:04 UTC, LeoWikstrom commented on StortSpelProjekt/Sandbox/src/main.cpp
> +    audiotest.OpenFile(engine.GetAudioEngine(), TEXT("../Vendor/Resources/Audio/AGameWithNoName.wav"));
Bra val av musik

2020-09-09 13:18 UTC, LeoWikstrom submitted a review, later dismissed

2020-09-10 08:58 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.h
> +#define fourccDPDS 'sdpd'
Add comment to what this is.

2020-09-10 08:59 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.h
> +	IXAudio2SourceVoice* m_pSourceVoice;
What is a audiosourcevoice

2020-09-10 08:59 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.h
> +	HRESULT m_Hr;
If these are relevant to the engineSystem, explain what they are.

2020-09-10 09:00 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.h
> +	HRESULT findChunk(HANDLE hFile, DWORD fourcc, DWORD& dwChunkSize, DWORD& dwChunkDataPosition);
Brief explination in the .h file what it does

2020-09-10 09:00 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/Audio.h
> +	HRESULT readChunkData(HANDLE hFile, void* buffer, DWORD buffersize, DWORD bufferoffset);
Brief explination in the .h file what it does

2020-09-10 09:00 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/AudioEngine.cpp
> +	m_pMasterVoice = nullptr;
What is different with master voice.

2020-09-10 09:01 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/AudioEngine.cpp
> +	m_pXAudio2 = nullptr;
My understanding is that audio2 is the "heart" of the audio system?

2020-09-10 09:02 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/AudioEngine.h
> +	IXAudio2* m_pXAudio2;
"heart" of the audio play system?

2020-09-10 09:03 UTC, fjz345 commented on StortSpelProjekt/Engine/src/AudioEngine/AudioEngine.h
> +	IXAudio2MasteringVoice* m_pMasterVoice;
Master voice handles other voices? How is this used.

2020-09-10 09:04 UTC, fjz345 commented on StortSpelProjekt/Engine/src/Engine.h
> +	IXAudio2* const GetAudioEngine() const;
Create a AudioEngine* instead of a IXAudio2*

2020-09-10 09:07 UTC, fjz345 commented on StortSpelProjekt/Sandbox/src/main.cpp
> +    audiotest.OpenFile(engine.GetAudioEngine(), TEXT("../Vendor/Resources/Audio/AGameWithNoName.wav"));
Testing is fine. engine.GetAudioEngine() should not be in main.cpp, instead create something like AudioEngine.CreateSound(string path) which returns a Audio.

2020-09-10 09:07 UTC, fjz345 reviewed
Change commented parts :)

2020-09-10 12:10 UTC, LeoWikstrom submitted a review, later dismissed

2020-09-10 12:46 UTC, fjz345 commented on StortSpelProjekt/Sandbox/src/main.cpp
> +    audiotest.OpenFile(engine.GetAudioEngine()->GetAudioEngine(), TEXT("../Vendor/Resources/Audio/AGameWithNoName.wav"));
Just remove this test and we can approve again.

2020-09-10 13:15 UTC, LeoWikstrom approved these changes

2020-09-10 13:15 UTC, fjz345 approved these changes

2020-09-10 13:15 UTC, merged