Sword swing sound effect added
jocke1995/StortSpelProjekt pull request #133
Opened 2020-10-20 14:45 UTC by jakkeez

Sword swing sound effect added when player presses left click. Test by running the Jacob test scene and pressing left click will play a *swing" sound.

2020-10-20 15:33 UTC, jocke1995 approved these changes, later dismissed
works

2020-10-21 06:40 UTC, Schtekt requested changes
The idea itself is good, but needs some rethinking on how it is executed. Meleecomponent should not assume that it has an audiocomponent from it's parent.

2020-10-21 06:40 UTC, Schtekt commented on StortSpelProjekt/Sandbox/src/main.cpp
> +    Scene* jacobScene = JacobsTestScene(sceneManager);
Make sure to comment out "fredrikScene" or your own before merge.

2020-10-21 06:40 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +
Assuming that there will be a swordswing makes other scenes crash.
What would happen if an enemy has a meleecomponent and does not use this sound?

2020-10-21 06:40 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +	m_MeleeTransformModified = *m_pMeleeTransform;
Love the namechange!

2020-10-21 06:40 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +		m_pVoiceComponent->Play(L"SwordSwing");
Again, assuming that the component has this sound.

2020-10-21 07:38 UTC, Schtekt approved these changes

2020-10-21 08:06 UTC, jocke1995 approved these changes

2020-10-21 08:07 UTC, merged