Input class
jocke1995/StortSpelProjekt pull request #14
Opened 2020-09-09 10:56 UTC by LeoWikstrom

An class for input has been created and RAW input has been implemented. Controls have not been implemented, only input, so don't expect anything to move when pressing the keys or moving the mouse

2020-09-09 14:01 UTC, kattalainen requested changes

2020-09-09 14:01 UTC, kattalainen commented on StortSpelProjekt/Engine/src/Misc/Window.cpp
> +			OutputDebugString(TEXT("GetRawInputData does not return correct size !\n"));
Block :>

2020-09-09 14:01 UTC, kattalainen commented on StortSpelProjekt/Engine/src/Input/Input.h
> +enum class SCAN_CODES
Enums börjar med E_ eller F_ ?

2020-09-09 14:01 UTC, kattalainen commented on StortSpelProjekt/Engine/src/Input/Input.h
> +enum class MOUSE_BUTTON
enum namnkonvention

2020-09-09 14:08 UTC, kattalainen submitted a review, later dismissed

2020-09-09 15:00 UTC, fjz345 commented on StortSpelProjekt/Sandbox/src/main.cpp
> +    Input::GetInstance().RegisterDevices(window->GetHwnd());
Do this higher up since this is an init() type function. Would suggest right under engine.init().

2020-09-09 15:06 UTC, fjz345 commented on StortSpelProjekt/Engine/src/Misc/Window.cpp
> +			Input::GetInstance().SetMousePosition(inputData.lLastX, inputData.lLastY);
inputData.lLastX/Y is how much the mouse moved in x/y which does not correlate the the function names "SetMousePosition" and member variable "m_MousePos"

2020-09-09 15:06 UTC, fjz345 submitted a review, later dismissed

2020-09-10 09:01 UTC, kattalainen approved these changes

2020-09-10 09:17 UTC, jakkeez approved these changes

2020-09-10 09:21 UTC, merged