Jump Tweak
jocke1995/StortSpelProjekt pull request #144
Opened 2020-10-22 13:30 UTC by Anteanten

Made the jump a bit faster. It can be changed in player input for any future tweaks.

It is only in game!

2020-10-22 13:59 UTC, Schtekt requested changes
Love it, though for some reason the jump isn't registered in sandbox scenes anymore?

2020-10-22 14:10 UTC, Schtekt requested changes

2020-10-22 14:10 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/PlayerInputComponent.cpp
> +	m_Gravity = (-2 * m_JumpHeight) / (m_JumpTime * m_JumpTime);
Please tweak the values and adjust the gravity calculation

2020-10-23 08:24 UTC, Schtekt submitted a review, later dismissed

2020-10-23 11:43 UTC, LeoWikstrom submitted a review, later dismissed
Seems to work nicely 👍

2020-10-23 11:58 UTC, Schtekt approved these changes

2020-10-23 12:00 UTC, LeoWikstrom approved these changes

2020-10-23 12:00 UTC, merged