Tweak enemy damage
jocke1995/StortSpelProjekt pull request #151
Opened 2020-10-23 12:21 UTC by kattalainen

Enemy damage can now be set when creating enemies. Made default to 10 damage.

2020-10-23 12:32 UTC, Schtekt requested changes
Looking good! 10 is a good number for dmg.

Dont forget to merge develop though!

2020-10-23 12:35 UTC, LeoWikstrom approved these changes, later dismissed
Looks good 👍

2020-10-23 12:35 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/EnemyFactory.cpp
> +Entity* EnemyFactory::AddEnemy(const std::string& entityName, Model* model, int hp, float3 pos, const std::wstring& sound3D, unsigned int compFlags, unsigned int aiFlags, float scale, float3 rot, con
When merging in develop, make sure this addition is also added to the DefineEnemy() function

2020-10-23 13:33 UTC, LeoWikstrom submitted a review, later dismissed

2020-10-26 08:26 UTC, Schtekt approved these changes

2020-10-26 08:32 UTC, LeoWikstrom approved these changes

2020-10-26 08:32 UTC, merged