Hit sound effect
jocke1995/StortSpelProjekt pull request #153
Opened 2020-10-23 14:49 UTC by jakkeez

Added effect when hitting the enemy with either a projectile or the "sword" melee  attack. Simply run the program and hit them with either and hear the "bruh" sound effect

2020-10-23 15:36 UTC, kattalainen submitted a review, later dismissed
There is some hardcoded stuff in here that will need some fixing, but for the purposes of the internal testing I will approve :>

2020-10-26 08:12 UTC, LeoWikstrom requested changes

2020-10-26 08:12 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/Components/ProjectileComponent.cpp
> +			if (event->ent2->GetName().find("conan") != std::string::npos && event->ent2->GetComponent<component::Audio3DEmitterComponent>())
I am not happy with this hard coded enemy name. If you disagree, dismiss this review

2020-10-26 09:14 UTC, LeoWikstrom approved these changes

2020-10-26 09:14 UTC, kattalainen approved these changes

2020-10-26 09:15 UTC, merged