Removal of enemies on death.
jocke1995/StortSpelProjekt pull request #158
Opened 2020-10-26 08:53 UTC by Schtekt

Removes enemies after a specified time after death.
Also added so that projectiles are removed after a certain time from creation.

2020-10-26 14:46 UTC, jakkeez requested changes
Crash, plz fix bro

2020-10-26 14:50 UTC, jakkeez submitted a review, later dismissed

2020-10-26 15:07 UTC, jakkeez approved these changes, later dismissed

2020-10-27 09:50 UTC, jakkeez submitted a review, later dismissed

2020-10-27 14:11 UTC, jakkeez approved these changes
Good work. Whoever thought to implement two separate events for death and removal of entity is a genius !!

2020-10-27 14:12 UTC, fredrix96 approved these changes
Seems to work as intended

2020-10-27 14:13 UTC, merged