Teleporter to shopscene and back
jocke1995/StortSpelProjekt pull request #159
Opened 2020-10-26 11:10 UTC by jocke1995

Walk into the teleporter to get teleported back. 

Known bug (not to be solved in this task) : A sphere spawns in origo when shooting after changing scene.

2020-10-26 13:06 UTC, Anteanten submitted a review, later dismissed

2020-10-26 14:39 UTC, Schtekt requested changes
Jacobscene crashes in sandbox.

2020-10-27 09:00 UTC, Anteanten approved these changes, later dismissed

2020-10-27 09:45 UTC, Schtekt requested changes

2020-10-27 09:45 UTC, Schtekt commented on StortSpelProjekt/Sandbox/src/main.cpp
>      //Scene* timScene = TimScene(sceneManager);
Where did "Scene* activeScenes[] = { leoScene };" go? Please return it :)

2020-10-27 09:49 UTC, Schtekt approved these changes

2020-10-27 09:51 UTC, Anteanten approved these changes

2020-10-27 09:51 UTC, merged