Currency on Death
jocke1995/StortSpelProjekt pull request #163
Opened 2020-10-26 15:38 UTC by jakkeez

When enemies die they now drop currency, the currency is specified by type and amount in currency component.

2020-10-26 16:53 UTC, kattalainen requested changes, later dismissed
just move the currency includes to gamecomponent.h then it's fine

2020-10-26 16:53 UTC, kattalainen commented on StortSpelProjekt/Game/src/main.cpp
> +#include "Gamefiles/Components/CurrencyComponent.h"
you can include this in GameComponents.h instead :>

2020-10-26 16:53 UTC, kattalainen commented on StortSpelProjekt/Sandbox/src/main.cpp
> +#include "Components/CurrencyComponent.h"
GameComponents.h !

2020-10-27 08:34 UTC, kattalainen approved these changes

2020-10-27 09:52 UTC, OtakuFreak13 approved these changes
Runs and seems to add currency to player.

2020-10-27 13:26 UTC, merged