NavMesh in Game
jocke1995/StortSpelProjekt pull request #166
Opened 2020-10-27 14:20 UTC by LeoWikstrom

2020-10-27 15:25 UTC, OtakuFreak13 submitted a review, later dismissed
Runs fine

2020-10-27 15:43 UTC, jakkeez approved these changes

2020-10-27 15:45 UTC, jakkeez requested changes
Merge with develop before pullrequest is accepted

2020-10-28 07:53 UTC, OtakuFreak13 approved these changes

2020-10-28 08:12 UTC, jakkeez approved these changes

2020-10-28 08:13 UTC, merged