Sprint tweak
jocke1995/StortSpelProjekt pull request #177
Opened 2020-10-28 14:47 UTC by jakkeez

2020-10-28 15:03 UTC, LeoWikstrom approved these changes, later dismissed

2020-10-28 15:31 UTC, LeoWikstrom approved these changes, later dismissed

2020-10-28 15:55 UTC, kattalainen commented on StortSpelProjekt/Game/src/main.cpp
>      melc = entity->AddComponent<component::MeleeComponent>();
on row 172, could you please add this:     melc->SetDamage(10);
this somehow got lost in merges, thank you!

2020-10-28 16:00 UTC, kattalainen commented on StortSpelProjekt/Game/src/Gamefiles/Components/PlayerInputComponent.cpp
> +				vel = { forward.x * m_MovementSpeed * DASH_MOD, forward.y, forward.z * m_MovementSpeed * DASH_MOD };
plz tone down the dash a bit, you can now glitch through the thick outer walls and into the ground in the "inside area"

2020-10-28 16:26 UTC, kattalainen submitted a review, later dismissed

2020-10-28 16:42 UTC, fjz345 requested changes
Change resolution. Then also tweeks that should be made:
1. Fullscreen
2. Camera distance to player
3. Mouse sensitivity?

2020-10-28 16:42 UTC, fjz345 commented on StortSpelProjekt/Vendor/config.txt
> +i_resolutionWidth 1921
1920

2020-10-29 07:07 UTC, fjz345 approved these changes

2020-10-29 07:08 UTC, kattalainen approved these changes

2020-10-29 07:09 UTC, merged