Only 1 scene active, uninit runs.
jocke1995/StortSpelProjekt pull request #180
Opened 2020-11-02 10:54 UTC by fjz345

2020-11-02 12:46 UTC, jakkeez approved these changes, later dismissed

2020-11-02 14:18 UTC, fredrix96 requested changes

2020-11-02 14:18 UTC, fredrix96 commented on StortSpelProjekt/Engine/src/ECS/SceneManager.h
> +	Scene* m_DefaultScene;
Code standard. It should be m_pDefaultScene

2020-11-02 16:36 UTC, fjz345 commented on StortSpelProjekt/Engine/src/ECS/SceneManager.h
> +	Scene* m_DefaultScene;
fixed

2020-11-02 16:55 UTC, fredrix96 approved these changes
Works fine

2020-11-03 08:18 UTC, jakkeez approved these changes

2020-11-03 08:18 UTC, merged