Level kill goal
jocke1995/StortSpelProjekt pull request #182
Opened 2020-11-02 13:57 UTC by Anteanten

This feature adds a goal to kill X amount of enemies before the portal spawns

2020-11-02 16:00 UTC, Schtekt requested changes
When the player dies the bar goes up. Is it possible to avoid this? otherwise I love it!

2020-11-02 16:11 UTC, OtakuFreak13 approved these changes, later dismissed
Code looks good. Tested 3 "levels" and worked as intended. 
We now have game loop nice!

2020-11-03 08:41 UTC, OtakuFreak13 approved these changes

2020-11-03 08:53 UTC, Schtekt approved these changes
All good

2020-11-03 08:53 UTC, merged