It is now possible to update texts and quads during runtime
jocke1995/StortSpelProjekt pull request #183
Opened 2020-11-02 14:36 UTC by fredrix96

The text and quad is updated in FredriksTestScene

2020-11-02 16:23 UTC, OtakuFreak13 requested changes

2020-11-02 16:23 UTC, OtakuFreak13 commented on StortSpelProjekt/Engine/src/ECS/Components/GUI2DComponent.h
>  		QuadManager m_pQuadMan;
Only pointers should have _p as part of their name

2020-11-03 08:28 UTC, Schtekt requested changes
Shop scene in sandbox crashes. Seems as there are no entities when it searches for a specific entity.
Looks like it was removed in develop, so try merging with develop first.
Everything else seems fine though :D

2020-11-03 09:47 UTC, OtakuFreak13 approved these changes

2020-11-03 09:56 UTC, Schtekt approved these changes

2020-11-03 09:56 UTC, merged