Animation backend code
jocke1995/StortSpelProjekt pull request #184
Opened 2020-11-02 15:06 UTC by LeoWikstrom

The animation code from last sprint

2020-11-02 16:35 UTC, fredrix96 requested changes, later dismissed
Code seems fine and the animation is displayed as it should, however, the shop scene in Sandbox crashes

2020-11-02 17:03 UTC, fredrix96 submitted a review, later dismissed
Seems fine. Good job!

2020-11-03 08:16 UTC, jocke1995 commented on StortSpelProjekt/Engine/src/Headers/structs.h
> +#define MAX_ANIMATION_MATRICES 52
Should not be 52

2020-11-03 08:22 UTC, jocke1995 requested changes
Minor change that you need to fix

2020-11-03 14:11 UTC, jocke1995 commented on StortSpelProjekt/Sandbox/src/main.cpp
> +Scene* ShopScene(SceneManager* sm);
Why did you add this again? :/ Remove from sandbox

2020-11-03 14:12 UTC, jocke1995 requested changes
Change

2020-11-04 08:36 UTC, jocke1995 approved these changes

2020-11-04 08:43 UTC, fredrix96 approved these changes
Looks good, good work!

2020-11-04 08:43 UTC, merged