Particle classes
jocke1995/StortSpelProjekt pull request #192
Opened 2020-11-04 10:07 UTC by fjz345

Feel free to test. I tested with just printing stuff out.

2020-11-04 10:45 UTC, fredrix96 requested changes
Sandbox does not run because of a redefinition of a Scene

2020-11-04 10:55 UTC, Anteanten commented on StortSpelProjekt/Sandbox/src/main.cpp
> +    Scene* filipScene = FloppipTestScene(sceneManager);
sandbox scene fungerar ej då andra scener inte är komenterad ut

2020-11-04 11:14 UTC, fjz345 commented on StortSpelProjekt/Sandbox/src/main.cpp
> +    Scene* filipScene = FloppipTestScene(sceneManager);
fixed

2020-11-04 11:58 UTC, Anteanten submitted a review, later dismissed

2020-11-05 12:00 UTC, fredrix96 submitted a review, later dismissed

2020-11-05 12:29 UTC, fredrix96 approved these changes

2020-11-05 12:29 UTC, Anteanten approved these changes

2020-11-05 12:31 UTC, merged