GUI Health
jocke1995/StortSpelProjekt pull request #197
Opened 2020-11-05 11:18 UTC by fredrix96

Make sure that it looks fine in FredriksTestScene and Game and that you are able to gain health by the health gain upgrade in Game

2020-11-05 11:53 UTC, jakkeez submitted a review, later dismissed

2020-11-05 13:32 UTC, Whixx requested changes
Crashes on death. Make it not.

2020-11-05 14:28 UTC, Whixx approved these changes, later dismissed

2020-11-05 16:19 UTC, Whixx approved these changes, later dismissed

2020-11-05 16:21 UTC, Whixx submitted a review, later dismissed

2020-11-05 16:40 UTC, jocke1995 requested changes
Maxhealth doesn't update when buying hp in shopScene. Pls fix, I would also see the gui to be just a tiny bit smaller but I am not an artist so dont do that if you dont want to :))))))))))))))))))))))))

2020-11-06 08:28 UTC, Whixx requested changes

2020-11-06 08:28 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/GameGUI.cpp
> +	m_OldCurrHealth = 0;
This name does not make sense.

2020-11-06 08:54 UTC, Whixx submitted a review, later dismissed

2020-11-06 09:10 UTC, jocke1995 commented on StortSpelProjekt/Game/src/Gamefiles/GameGUI.h
> +	Scene* m_OldScene;
m_pOldScene

2020-11-06 09:11 UTC, jocke1995 requested changes
Fix

2020-11-06 09:24 UTC, jocke1995 approved these changes
good

2020-11-06 09:25 UTC, Whixx approved these changes

2020-11-06 09:31 UTC, merged