Camera Distance Lock
jocke1995/StortSpelProjekt pull request #198
Opened 2020-11-05 12:09 UTC by jakkeez

The camera now respects boundaries and "zooms in" when it hits a wall or floor. 
The camera distance can be changed in playerinput header file, in a define.
Test by going into game and moving around, turning the camera and walking up to the wall to see if it clips, if it doesnt, the implementation works.

2020-11-05 14:41 UTC, jocke1995 commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.h
> +		void SetAttackInterval(float interval);
I think this change made something in main.cpp not to compile. In main you still write this with lowerCase S. I had to comment out that line to compile the code

2020-11-05 14:43 UTC, jocke1995 requested changes
1. Didn't compile in main because of new name of setAttackIntervall.
2. Talk to me (Joakim), I found some bugs with the camera clipping that we can discuss when you get back to solve this 👍

2020-11-06 09:31 UTC, Whixx reviewed
Camera sensitivity "goes up" when the camera zooms.

2020-11-06 13:40 UTC, Whixx submitted a review, later dismissed
Good work!

2020-11-06 13:57 UTC, jocke1995 approved these changes, later dismissed
Works, just 1 small clipping which we discussed when I reviewed this. But I think its fine! gj

2020-11-06 14:21 UTC, Whixx approved these changes

2020-11-06 14:21 UTC, jocke1995 approved these changes
works good

2020-11-06 14:21 UTC, merged