Connected game over scene to main menu with some fixes along the way.
jocke1995/StortSpelProjekt pull request #206
Opened 2020-11-10 07:01 UTC by Schtekt

2020-11-10 08:49 UTC, Anteanten submitted a review, later dismissed
Currency återställs inte till 0 efter en gameover

2020-11-10 12:23 UTC, LeoWikstrom requested changes, later dismissed
Works well. One thing about the Game Over scene though: The Exit button should be further to the right and seven pixels (on my screen at least) further down

2020-11-10 12:23 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/main.cpp
>      if (ImGuiHandler::GetInstance().GetBool("reset"))
Maybe call the reset functions here? 😁

2020-11-11 08:35 UTC, LeoWikstrom submitted a review, later dismissed
👌🏽

2020-11-11 08:48 UTC, Anteanten requested changes
Upgrades or shop does not reset through runs

2020-11-11 14:20 UTC, LeoWikstrom submitted a review, later dismissed

2020-11-11 15:17 UTC, LeoWikstrom approved these changes

2020-11-11 15:17 UTC, Anteanten approved these changes

2020-11-11 15:17 UTC, merged