Upgrade GUI menu
jocke1995/StortSpelProjekt pull request #210
Opened 2020-11-10 16:59 UTC by OtakuFreak13

Hit "u" to open up the menu. 
When an upgrade is bought you can click on the upgrade "buttons"  that appear in the menu to show their description.
This menu will NOT update if you buy an upgrade while the menu is open.
Just close and open the menu again to reload.

To check the function for cycling through all upgrades, if you have more than 10 upgrades. You have to uncomment  the map called vec and change which forloop in comment  in update() and createMenu().

2020-11-11 09:18 UTC, LeoWikstrom requested changes
Works well overall. The HealthBoost actually seems to give 20 extra hp, and maybe it should be mentioned that it's 20 per level? But maybe that is not really part of this task 😅 It would, however, be nice to see the level of the upgrade as well

2020-11-11 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/UpgradeGUI.cpp
> +			int itterator = 0;
Iterator is spelled with one 't' 😘

2020-11-11 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/UpgradeGUI.cpp
> +			int posItterator = 0;
Same here 😁

2020-11-11 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/UpgradeGUI.cpp
> +	int itterator = 0;
One 't'

2020-11-11 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/UpgradeGUI.h
> +	SceneManager* m_Sm = nullptr;
Pointers. Should be called m_pCurrentScene and m_pSm

2020-11-11 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/UpgradeGUI.h
> +	Texture* m_buttonParchment;
Capital letter after m_
Also, divider is spelled with an 'i'

2020-11-11 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/main.cpp
> +	zombie.hp = 1;
Don't forget to change this back

2020-11-11 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/main.cpp
> +    /* ------------------------ GUI END ---------------------------- */
Thank you for adding the "END"

2020-11-11 10:58 UTC, OtakuFreak13 commented
> 
> 
> Works well overall. The HealthBoost actually seems to give 20 extra hp, and maybe it should be mentioned that it's 20 per level? But maybe that is not really part of this task 😅 It would, however, be nice to see the level of the upgrade as well

This is a bug that I just found when reviewing Tims "Potion of strength" upgrade where someone has added an increase in level when an upgrade is bought for the first time in the shop. This then leads to the upgrade being applied twice since it is applied and then increased in level which then applies it again. Just pushed a fix for this.

Yeah I should definitely add the level of the upgrade to the description.

2020-11-11 13:00 UTC, kattalainen commented
Like Leo said it would be nice to see what level the upgrades are :> 
Besides this I have also noticed a bug in the game scene where I get sent back to the main menu for some reason, I will try to find a way of reproducing the bug.

2020-11-11 14:18 UTC, LeoWikstrom submitted a review, later dismissed

2020-11-11 16:57 UTC, kattalainen approved these changes

2020-11-12 08:33 UTC, LeoWikstrom approved these changes

2020-11-12 08:34 UTC, merged