Crosshair and aiming
jocke1995/StortSpelProjekt pull request #216
Opened 2020-11-11 15:33 UTC by fredrix96

Make sure that you can aim towards the crosshair in Game. It is not perfect, mostly because the spawn point of the projectile is below the crosshair, but it is good enough for headshots ;)

2020-11-11 16:09 UTC, OtakuFreak13 approved these changes, later dismissed

2020-11-12 08:47 UTC, Schtekt requested changes
Ser bra ut generellt!
Efter diskussion med Fredrik så bestämde vi att distansen som strålen kastas inte borde vara 100 varje gång utan borde vara beroende på projektilens hastighet och tid som den lever. Justeringar på g!

2020-11-12 08:57 UTC, Schtekt approved these changes
Perfect!

2020-11-12 09:02 UTC, OtakuFreak13 approved these changes

2020-11-12 09:03 UTC, merged