ImprovedAI
jocke1995/StortSpelProjekt pull request #228
Opened 2020-11-17 10:01 UTC by LeoWikstrom

Zombies no longer move in big bunches. Will strafe around player until attacking opportunity presents itself. They are still stupid as fuck

2020-11-17 10:20 UTC, Anteanten requested changes, later dismissed
Sometimes the ranged enemies get really shy and start facing the wall refusing to leave. Maybe turn around sometimes to fire a shot

2020-11-17 10:57 UTC, fjz345 reviewed
l

2020-11-18 08:42 UTC, Anteanten approved these changes, later dismissed
Very brave demons

2020-11-18 10:10 UTC, Anteanten approved these changes

2020-11-18 15:40 UTC, jakkeez approved these changes

2020-11-18 15:40 UTC, merged