Re-roll function in shop
jocke1995/StortSpelProjekt pull request #241
Opened 2020-11-19 09:11 UTC by jakkeez

The re-roll is now implemented in the shop, the button costs 50 currency to use and is a flat price (i.e no price increase, this is subject to change) 
Try by beating a level and re-roll in the shop, also try to buy some upgrades and make sure that they do not reset down to zero if re-rolled.

2020-11-19 10:04 UTC, LeoWikstrom submitted a review, later dismissed

2020-11-19 14:27 UTC, fjz345 requested changes, later dismissed
You mentioned that it is fixed 50, There is no task to change it later. I want you to implement a way to change the price with each re-roll. The exact price and price change can then be changed easily later. (ex, function called "rerollCost = rerollCostIncreaseFunction(int changedTimes)")

2020-11-19 14:27 UTC, fjz345 commented on StortSpelProjekt/Game/src/Gamefiles/Shop.h
> +
make it a variable

2020-11-19 14:27 UTC, fjz345 commented on StortSpelProjekt/Game/src/Gamefiles/Shop.h
> +	void updateShop();
Other name than updateShop(), sounds like it should refresh the ui/logic of the shop but it also randomizes the inventory of the shop.

2020-11-20 10:18 UTC, LeoWikstrom requested changes, later dismissed
Code looks good. Consider removing empty space on icon, as it is now possible to click outside the dark area of the button. Also, the price of a re-roll should be reset when the player dies, this should be done in Player's onResetGame function

2020-11-20 12:26 UTC, fjz345 approved these changes
Looking good, either you or the next person who changes the base price will have to change it in more than 1 place though, either const int ___ = 50 or #define ____ 50

2020-11-20 14:50 UTC, LeoWikstrom approved these changes

2020-11-20 14:50 UTC, merged