Particle Emitter can have multiple effects
jocke1995/StortSpelProjekt pull request #251
Opened 2020-11-23 11:31 UTC by fjz345

2020-11-23 17:17 UTC, jocke1995 commented on StortSpelProjekt/Game/src/Gamefiles/Components/PoisonDebuff.cpp
> +	parent->AddComponent<component::ParticleEmitterComponent>(&settings, true);
Separate constructor for this is nice, but what happens if I want to add another particle effect to this component somewhere else? I cannot find any function calls to append a particleEffect to an existing component. Is the only way to add an effect to create all the effects directly in the constructor?

2020-11-23 17:18 UTC, jocke1995 requested changes
Some questions about appending particle effects to a component without calling constructor.

2020-11-24 09:38 UTC, jocke1995 approved these changes

2020-11-24 10:41 UTC, Anteanten approved these changes

2020-11-24 10:41 UTC, merged