EdgeClass
jocke1995/StortSpelProjekt pull request #254
Opened 2020-11-24 13:20 UTC by LeoWikstrom

Added class for edges between room. This class keeps track of which edges are connected, and which entities and NavTriangles belong to each edge. To test, insert the following code:

In the main loop, add:

	static int toRemove = 0;
        static bool pressedEnter = false;

        if (Input::GetInstance().GetKeyState(SCAN_CODES::ENTER))
        {
            pressedEnter = true;
        }
        if (!Input::GetInstance().GetKeyState(SCAN_CODES::ENTER) && pressedEnter)
        {
            pressedEnter = false;
            AssetLoader::Get()->GetEdges().at(toRemove)->RemoveEntitiesFromWorld();
            toRemove = (toRemove + 1) % AssetLoader::Get()->GetEdges().size();
        }

Where the scene is loaded in main (where the function LoadMap is called), replace the LoadMap call with the following:
	al->LoadMap(scene, "../Vendor/Resources/BaseRoom.map", 0);
    	al->LoadMap(scene, "../Vendor/Resources/ExampleRoom.map", 1, { 173.0, 0.0, 0.0 });
    	al->LoadMap(scene, "../Vendor/Resources/ExampleRoom.map", 2, { 86.5, 0.0, 150.0 });
    	al->LoadMap(scene, "../Vendor/Resources/ExampleRoom.map", 3, { -173.0, 0.0, 0.0 });
    	al->LoadMap(scene, "../Vendor/Resources/ExampleRoom.map", 4, { -259.5, 0.0, 150.0 });
    	al->LoadMap(scene, "../Vendor/Resources/ExampleRoom.map", 5, { -173.0, 0.0, 300.0 });
    	al->LoadMap(scene, "../Vendor/Resources/ExampleRoom.map", 6, { 0.0, 0.0, 300.0 });

In GameInitScene() add:

    std::vector<Edge*> edges = AssetLoader::Get()->GetEdges();
    edges.at(0)->RemoveEntitiesFromWorld();
    edges.at(1)->RemoveEntitiesFromWorld();
    edges.at(4)->RemoveEntitiesFromWorld();
    edges.at(10)->RemoveEntitiesFromWorld();
    edges.at(11)->RemoveEntitiesFromWorld();
    edges.at(14)->RemoveEntitiesFromWorld();
    edges.at(15)->RemoveEntitiesFromWorld();
    edges.at(17)->RemoveEntitiesFromWorld();
    edges.at(19)->RemoveEntitiesFromWorld();
    edges.at(23)->RemoveEntitiesFromWorld();
    edges.at(24)->RemoveEntitiesFromWorld();
    edges.at(26)->RemoveEntitiesFromWorld();
    edges.at(31)->RemoveEntitiesFromWorld();
    edges.at(33)->RemoveEntitiesFromWorld();
    edges.at(38)->RemoveEntitiesFromWorld();
    edges.at(40)->RemoveEntitiesFromWorld();

2020-11-24 15:39 UTC, Schtekt requested changes
Looks good!
A few minor things I would like to change or take a further gander at.

2020-11-24 15:39 UTC, Schtekt commented on StortSpelProjekt/Engine/src/Renderer/Renderer.cpp
> +	gpsdShadow.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
Backface culling should not be off right?

2020-11-24 15:39 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/RangeComponent.cpp
> +
This is unneccessary, right?

2020-11-25 10:12 UTC, Schtekt submitted a review, later dismissed

2020-11-25 15:46 UTC, kattalainen submitted a review, later dismissed
This rar file is probably not needed: StortSpelProjekt/Vendor/Resources/Models/Torch.rar.
Other than that it's looking good!

2020-11-26 07:17 UTC, Schtekt approved these changes

2020-11-26 09:52 UTC, kattalainen approved these changes

2020-11-26 09:53 UTC, merged