MapGeneration
jocke1995/StortSpelProjekt pull request #255
Opened 2020-11-24 13:26 UTC by LeoWikstrom

Maps are now procedurally generated. Try starting the game a number of times and see the different levels generated. THE ROOMS THEMSELVES ARE NOT A PART OF THIS PULL REQUEST, DO NOT REVIEW THEM HERE!

2020-11-25 09:12 UTC, Anteanten approved these changes, later dismissed

2020-11-25 09:25 UTC, Anteanten submitted a review, later dismissed

2020-11-25 16:21 UTC, jocke1995 commented on StortSpelProjekt/Engine/src/Renderer/HLSL/ForwardPixel.hlsl
>  	finalColor += ambient;
Change this back to 0.004f. Fredrik told me to say that he changed this temporary and forgot to change them back.

2020-11-25 16:22 UTC, jocke1995 commented on StortSpelProjekt/Game/src/Gamefiles/Components/RangeComponent.cpp
> +		Log::Print("Playerpos: %f, %f, %f\n", ParentPos.x, ParentPos.y, ParentPos.z);
remove this

2020-11-25 16:25 UTC, jocke1995 requested changes, later dismissed
A few questions about some stuff. Also, game is currently bugged, all the lights are in origo. If the old scene should be removed. You have to fix the teleport and enemies before this task can be added into game. Since right now, if we merge this, we wont have a game until another user story is completed.

2020-11-26 09:25 UTC, Anteanten approved these changes

2020-11-26 10:39 UTC, jocke1995 submitted a review, later dismissed
DirectionalLight in game is removed.
Particles lagging, but might not be your fault.. the search has begun

2020-11-26 15:51 UTC, jocke1995 approved these changes
Ok even if the dir light in "game" is removed. But since we're gonna change into the new maps like.. right away.. it won't matter as you said :)

2020-11-26 17:17 UTC, closed without merging