Encryption of all models and decryption at runtime.
jocke1995/StortSpelProjekt pull request #258
Opened 2020-11-25 10:15 UTC by Schtekt

All files models are now encrypted!
If you want to run the game you need to download the new ignored models from the drive and place them in the "IgnoredModels" folder.

2020-11-25 16:33 UTC, Anteanten submitted a review, later dismissed

2020-11-26 09:34 UTC, jocke1995 commented on StortSpelProjekt/Engine/src/Renderer/Texture/Texture2D.cpp
> +	timer.StartTimer();
You probably forgot to remove these. Also remove the include at line 11

2020-11-26 09:36 UTC, jocke1995 requested changes
You forgot to remove some old code. Otherwise it seems to work good!

2020-11-26 13:18 UTC, jocke1995 approved these changes
good job

2020-11-26 13:22 UTC, Anteanten approved these changes

2020-11-26 13:22 UTC, merged