Smooth Animation Transitions
jocke1995/StortSpelProjekt pull request #262
Opened 2020-11-25 16:18 UTC by Whixx

Should be fully testable from game. The following animations should be visible:
Idle (when idle duh), Running (on movement), Axe Swing (on melee attack), Left hook (on ranged attack).

The animated model bug where some parts of the model were translated to origin is also solved.

2020-11-26 13:42 UTC, OtakuFreak13 requested changes
Just fix the minor code standard issue and I will approve.  Nicely done Wille!

2020-11-26 13:42 UTC, OtakuFreak13 commented on StortSpelProjekt/Engine/src/Renderer/AnimatedModel.h
> +    Animation* m_QueuedAnimation;
m_p Should be used for pointers.

2020-11-26 13:51 UTC, kattalainen reviewed
Seems fine, besides range animation only playing once when right mouse button is held down (as we discussed), the only issue I have is with the melee hitbox shrinking. Lets try and find a way to fix that before merge into develop.

2020-11-26 15:59 UTC, kattalainen submitted a review, later dismissed

2020-11-30 09:14 UTC, kattalainen approved these changes

2020-11-30 12:08 UTC, LeoWikstrom approved these changes
Some weird stuff with the animations, but the transitions are smooooth. Good job

2020-11-30 12:46 UTC, OtakuFreak13 approved these changes

2020-11-30 13:14 UTC, merged