Remove enemies which are outside the map
jocke1995/StortSpelProjekt pull request #286
Opened 2020-12-01 15:18 UTC by fredrix96

Paste this:
t->SetPosition(comps->pos.x, -5.0f /*comps->pos.y*/, comps->pos.z);
on row 188 in EnemyFactory.cpp.
If they all die, then it works

2020-12-01 17:04 UTC, jocke1995 commented on StortSpelProjekt/Game/src/Gamefiles/EnemyFactory.cpp
> +			m_TotalTime += 1.0f;
Use a float insttead to avoid calculations with modulo. In that case, you dont have to add +1.0 aswell. Otherwise, great work :)

2020-12-01 17:04 UTC, jocke1995 requested changes
Pls fix some minor issues :) otherwise, great work!

2020-12-01 17:20 UTC, jocke1995 approved these changes

2020-12-02 09:15 UTC, kattalainen approved these changes

2020-12-02 09:15 UTC, merged