Pillars, beams and banners
jocke1995/StortSpelProjekt pull request #309
Opened 2020-12-04 09:57 UTC by LeoWikstrom

Added pillars between walls, ceiling beams between rooms, and fixed z-fighting for the banners

2020-12-04 11:10 UTC, Anteanten requested changes
One pillar is Z-fighting
Roof is clipping with beam on outside room

2020-12-04 13:18 UTC, Schtekt requested changes
Generally looks good. I have a few problems though.
The beams that are in the ceiling seem to stretch their textures. Might just be my eyes tricking me but please take a look at that.

The beam between an empty room and a ramp room (in this case) seem to have light on it, or letting the ceiling through. See the attached image.
![image](https://user-images.githubusercontent.com/24506453/101168226-688d6780-363b-11eb-8333-a2680d1f4b57.png)

2020-12-04 15:51 UTC, Schtekt approved these changes

2020-12-07 08:07 UTC, Anteanten approved these changes

2020-12-07 08:08 UTC, merged