New shop
jocke1995/StortSpelProjekt pull request #312
Opened 2020-12-04 13:05 UTC by Schtekt

The shop room/environment has been updated :)

2020-12-04 13:49 UTC, jocke1995 submitted a review, later dismissed
Requests:
1. More lights on each wall
2. Change the direction of the moonLight so it fits the moon.
3. Also make sure that the shadow-map from the moon is locked and adjusted for the shop scene.

2020-12-04 14:42 UTC, kattalainen reviewed
I agree with Jocke about the lighting. 
Another thing is that when we spawn in the shop we are very close to the teleporter, and it might be too easy to accidentally move/dash into it.

2020-12-07 12:33 UTC, kattalainen submitted a review, later dismissed
Maybe still a little bit too dark around the shop itself, a light source above the shop might make it better but it's good enough for me :>

2020-12-07 15:35 UTC, kattalainen commented
not sure I like the candles, but that was part of another task right?

2020-12-08 09:10 UTC, kattalainen commented
Nevermind the lights, I think what I had a problem with is the tomb in the shop scene. Maybe put a "real" light source closer to it so it doesn't look like a dark void. The fact that the candles don't emit any light makes it look weird when they are in a very dark place such as the corner in the shop scene :> 
But you probably have better things to do atm, tell me your thought's and I'll probably just approve.

2020-12-08 10:27 UTC, LeoWikstrom requested changes
I personally think it looks weird without a shopkeeper. Might also be a good idea with a light on the "press f" sign? Would also like Stefan and Hasse banners 😁

2020-12-09 10:44 UTC, LeoWikstrom requested changes
Love the goblin. Would like it if you either added the goblin to the shop model (so both of them get highlighted) or move the highlight to the goblin. Otherwise, great job 👍🏽

2020-12-09 10:51 UTC, kattalainen commented
I think you went a bit overkill with the stefan and hans banners, check discord for rest of groups opinions

2020-12-09 12:50 UTC, kattalainen reviewed
I gotta say I don't really think the meme banners are fitting but I guess this is a good compromise and others are fine with it.
Just remove commented code and I'll approve

2020-12-09 12:50 UTC, kattalainen commented on StortSpelProjekt/Game/src/main.cpp
> +    //tc->SetTransformOriginalState();
I think you forgot to remove this.

2020-12-09 12:51 UTC, LeoWikstrom approved these changes, later dismissed
I wanted Stefan more to the left 😞

2020-12-09 13:25 UTC, Schtekt commented on StortSpelProjekt/Game/src/main.cpp
> +    //tc->SetTransformOriginalState();
Done

2020-12-09 13:27 UTC, LeoWikstrom approved these changes, later dismissed

2020-12-09 15:56 UTC, LeoWikstrom approved these changes

2020-12-09 16:03 UTC, jakkeez approved these changes
Works as intended. I dont mind the Stefan banner to be honest. But I would like to bring this up infront of everyone if this is such a split opinion. 
I will approve

2020-12-09 16:15 UTC, fredrix96 approved these changes
Cozy shop

2020-12-09 17:08 UTC, merged