Stop Moving You're Dead
jocke1995/StortSpelProjekt pull request #320
Opened 2020-12-08 08:46 UTC by Anteanten

Unsubcribes from everything in playerinput to prevent the player from performing actions when they have died.

The player can still do animations but  apparently a very nice fix will automagically work with Williams animation implementation in his branch so lets call this good enough?

2020-12-08 09:37 UTC, Schtekt requested changes, later dismissed

2020-12-08 09:37 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +#include "../Player.h"
This include is not used. Please remove it.

2020-12-08 10:09 UTC, LeoWikstrom submitted a review, later dismissed
Doesn't work properly. Animations are still played when dead. When player is killed by enemies (instead of by KILLPLAYER) she doesn't fall over

2020-12-09 10:35 UTC, LeoWikstrom approved these changes
Is fine

2020-12-09 13:21 UTC, Schtekt approved these changes

2020-12-09 13:22 UTC, merged