melee range increased
jocke1995/StortSpelProjekt pull request #343
Opened 2020-12-10 14:27 UTC by kattalainen

Increased base melee range (and the melee radius upgrade scaling) and moved the hitbox forwards a tiny bit. Screenshot of levels and sizes: https://drive.google.com/file/d/1nW-453elhavJXufAVmdJ0-puX8O_SnTl/view?usp=sharing

2020-12-10 14:41 UTC, fredrix96 approved these changes, later dismissed
Feels much better

2020-12-11 09:58 UTC, LeoWikstrom requested changes
Much better, though I have one remark

2020-12-11 09:58 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +	float distanceFromPlayer = m_HalfSize.z + (modelDim.z * parentTransform->GetScale().z);
This makes the bounding box appear at different distances from the player depending on the level of the upgrade. The following code should be better:
`float distanceFromPlayer = (m_HalfSize.z * m_ZScale) + (modelDim.z * parentTransform->GetScale().z / 2.0f);`

2020-12-11 10:53 UTC, LeoWikstrom approved these changes
Nice 👍🏽

2020-12-11 13:44 UTC, fredrix96 approved these changes

2020-12-11 13:44 UTC, merged