Balance patch
jocke1995/StortSpelProjekt pull request #358
Opened 2020-12-15 15:32 UTC by OtakuFreak13

Changed the pricing and balance of some of the upgrades.

2020-12-15 17:39 UTC, fredrix96 approved these changes, later dismissed
Seems more balanced

2020-12-16 08:01 UTC, Schtekt requested changes
Goodie!
I have left some comments about comments that I want to see changed, but otherwise good.

2020-12-16 08:01 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/UpgradeComponents/Upgrades/UpgradeMeleeDamage.cpp
>  	// now apply the new stat
Please remove this comment, it does not tell the reader anything.

2020-12-16 08:01 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/UpgradeComponents/Upgrades/UpgradeMeleeLifeSteal.cpp
> +// Lifesteal at these lvls 20% -> 25% -> 30% -> 35% -> 40%  -> 45%  -> 50%  -> 55%  -> 60%  -> 65%  -> 70%  -> 75%  -> 80%  -> 85%  -> 90%  -> 95%  -> 100%  etc.
The calculations and comments below show that the lifesteal percentage starts at 10%. Please decide on which you want to use.

2020-12-16 08:01 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/UpgradeComponents/Upgrades/UpgradePoisonAttack.cpp
> +	// -1 because the first level should start at 0.04
Please remove this comment. One should be able to see this in the calculations. It is also not mentioned in other upgrades. If it must remain, please add the same comment to the rest of the upgrades.

2020-12-16 08:01 UTC, Schtekt commented on StortSpelProjekt/Game/src/Gamefiles/Components/UpgradeComponents/Upgrades/UpgradePoisonAttack.cpp
> +	// -1 because the first level should start at 0.10.
Same as above.

2020-12-16 08:20 UTC, Schtekt approved these changes

2020-12-16 08:23 UTC, fredrix96 approved these changes

2020-12-16 08:23 UTC, merged