No thread limit and a true config file
jocke1995/StortSpelProjekt pull request #360
Opened 2020-12-16 10:45 UTC by fredrix96

Unlimited thread power! Oh, also, the config file is now a cfg file instead of a txt file

2020-12-16 16:29 UTC, kattalainen requested changes

2020-12-16 16:29 UTC, kattalainen commented on StortSpelProjekt/Vendor/config.cfg
> +f_brightness 2.0
I think you forgot to change this back :>

2020-12-16 16:42 UTC, kattalainen approved these changes
After playing a bit brightness 2.0 actually feels more nice :> sry I made you change it. Feel free to change it back if you want I'm approving anyway.

2020-12-17 07:26 UTC, Schtekt approved these changes
I see no problems, my computer actually got a good performance boost by this :D
Good initiative!

2020-12-18 11:16 UTC, merged