DemoScene in game
jocke1995/StortSpelProjekt pull request #52
Opened 2020-09-17 13:46 UTC by Schtekt

Added a demoscene in game where a player, a rock, a floor and a light is added. Showing off some of the work done in this sprint.

2020-09-17 13:52 UTC, OtakuFreak13 approved these changes, later dismissed
Code looks good and collison test works.

2020-09-17 14:19 UTC, jakkeez requested changes
Add more stuff like lights (shadows), more models and more moving objects
Code looks good

2020-09-17 15:28 UTC, OtakuFreak13 submitted a review, later dismissed
Demo scene looks good with new lighting.

2020-09-18 11:54 UTC, jakkeez approved these changes, later dismissed

2020-09-22 07:02 UTC, OtakuFreak13 approved these changes

2020-09-22 07:25 UTC, jakkeez approved these changes

2020-09-22 07:25 UTC, merged