Support for 3d audio
jocke1995/StortSpelProjekt pull request #53
Opened 2020-09-17 14:48 UTC by kattalainen

2020-09-17 15:23 UTC, Whixx commented on StortSpelProjekt/Engine/src/AudioEngine/AudioVoice.cpp
> +//#include "AudioEngine.h"
Remove if this serves no purpose

2020-09-17 15:25 UTC, Whixx commented on StortSpelProjekt/Engine/src/AudioEngine/AudioVoice.h
> +//#include <x3daudio.h>
Remove

2020-09-17 15:33 UTC, Whixx requested changes
Remove unnessecary comments and add some more comments describing steps in the code.

For example: "This for-loop goes through the sounds and checks if they are active"

2020-09-17 16:12 UTC, Whixx approved these changes, later dismissed
Make sure to look into the DPSSettings problem

2020-09-22 13:09 UTC, kattalainen commented
3d audio now supports multiple sources. Same source can be used for several entities, for both 3d and 2d components at the same time.

2020-09-23 06:41 UTC, Schtekt submitted a review, later dismissed
Just a few nitpicks with prints.
Otherwise, I see no faults in this (Though I am not well versed in audio...)

2020-09-23 06:41 UTC, Schtekt commented on StortSpelProjekt/Engine/src/ECS/Components/Audio3DEmitterComponent.cpp
> +		Log::PrintSeverity(Log::Severity::WARNING, "Tried to play Audio that has not been loaded!");
Would be great if the name of the sound was printed as well!
Also, don't forget to add a linebreak at the end of the warning.

2020-09-23 06:41 UTC, Schtekt commented on StortSpelProjekt/Engine/src/ECS/Components/Audio3DEmitterComponent.cpp
> +		Log::PrintSeverity(Log::Severity::WARNING, "Tried to stop Audio that has not been loaded!");
print the name and add line ending.

2020-09-23 06:41 UTC, Schtekt commented on StortSpelProjekt/Engine/src/ECS/Components/AudioVoiceComponent.cpp
>  		Log::PrintSeverity(Log::Severity::WARNING, "Tried to stop Audio that has not been loaded!");
Not your code, but would be nice if you could add the name of the sound and a line ending to this print.

2020-09-24 09:16 UTC, Whixx approved these changes, later dismissed
The audio is working fine and i couldn't find any coding errors. Good work.

2020-09-25 07:21 UTC, Schtekt approved these changes

2020-09-25 07:21 UTC, Whixx approved these changes

2020-09-25 07:22 UTC, merged