ImGui implemented
jocke1995/StortSpelProjekt pull request #65
Opened 2020-09-23 13:19 UTC by LeoWikstrom

Hold shift to release mouse

2020-09-23 14:04 UTC, OtakuFreak13 submitted a review, later dismissed
Both Game and sandbox runs. Code looks good.

2020-09-24 08:57 UTC, jocke1995 commented on StortSpelProjekt/Engine/src/ImGUI/ImGuiHandler.cpp
> +    }
Why create another scope for this?

2020-09-24 09:04 UTC, jocke1995 commented on StortSpelProjekt/Game/src/main.cpp
> +            }
Is this specific to DX12? If so, maybe put this inside renderers update function?

2020-09-24 09:06 UTC, jocke1995 commented on StortSpelProjekt/Sandbox/src/main.cpp
> +        }
Same here, can this be put inside Renderer? Since this is a "developerMode" config, maybe it shouldn't be visible in "main"?

2020-09-24 09:07 UTC, jocke1995 commented on StortSpelProjekt/Engine/src/ImGUI/ImGuiHandler.cpp
> +            ImGui::ColorEdit3("clear color", (float*)&m_Vec4Map["LightColor"]); // Edit 3 floats representing a color
c-style cast :(

2020-09-24 09:15 UTC, jocke1995 commented on StortSpelProjekt/Game/src/main.cpp
> +#include "ImGUI/ImGuiHandler.h"
Should this be included here? My thought was that the only thing we need to include here is "engine.h" and "game.h" later on?

2020-09-24 09:20 UTC, jocke1995 requested changes
It looks good and is easy to use.

2020-09-24 09:39 UTC, jocke1995 approved these changes, later dismissed
Nice.

2020-09-24 11:04 UTC, OtakuFreak13 submitted a review, later dismissed

2020-09-24 12:25 UTC, OtakuFreak13 approved these changes
Still runs with the changes.

2020-09-24 12:46 UTC, jocke1995 approved these changes

2020-09-24 12:48 UTC, merged