The program will now run with a maximum of four threads
jocke1995/StortSpelProjekt pull request #67
Opened 2020-09-23 14:40 UTC by fredrix96

The thread limit is set in Engine.h

2020-09-24 07:28 UTC, jocke1995 submitted a review, later dismissed
It is fine, but I thinks that it is enough to hardcode "maxNumThreads" since the only usage is for us developers before launch.

2020-09-24 07:43 UTC, OtakuFreak13 requested changes
Seems fine just change the comment I mentioned then we're good.

2020-09-24 07:43 UTC, OtakuFreak13 commented on StortSpelProjekt/Engine/src/Engine.cpp
> +	m_pThreadPool = new ThreadPool(numThreads); // Set num m_Threads to number of cores of the cpu
Change the comment on line 43 so it reflects the new code.

2020-09-25 08:56 UTC, OtakuFreak13 approved these changes

2020-09-25 08:58 UTC, jocke1995 approved these changes

2020-09-25 09:02 UTC, merged