PBR (all three tasks)
jocke1995/StortSpelProjekt pull request #68
Opened 2020-09-23 16:18 UTC by jocke1995

2020-09-24 12:56 UTC, LeoWikstrom submitted a review, later dismissed
Looks good

2020-09-24 14:30 UTC, OtakuFreak13 approved these changes, later dismissed

2020-09-24 14:59 UTC, OtakuFreak13 submitted a review, later dismissed

2020-09-25 06:45 UTC, LeoWikstrom requested changes
"Game" does not compile. The light in test scene needs to be updated

2020-09-25 07:19 UTC, LeoWikstrom approved these changes, later dismissed
Well done young padawan

2020-09-25 07:30 UTC, OtakuFreak13 approved these changes, later dismissed

2020-09-25 07:33 UTC, LeoWikstrom approved these changes

2020-09-25 07:33 UTC, OtakuFreak13 approved these changes

2020-09-25 07:33 UTC, merged