MeleeComponent
jocke1995/StortSpelProjekt pull request #82
Opened 2020-10-01 08:22 UTC by jakkeez

A meleecomponent that can be added to the player so the player can use left-click to "attack". When "Hitzone" collides with enemy entity, the entity (with a healthcomponent) dies (see console log output)

2020-10-01 12:44 UTC, Anteanten submitted a review, later dismissed

2020-10-01 12:49 UTC, Whixx commented on StortSpelProjekt/Engine/src/ECS/Components/BoundingBoxComponent.h
>  #include<DirectXCollision.h>
Should probably be a space here

2020-10-01 12:55 UTC, Whixx commented on StortSpelProjekt/Engine/src/Physics/Physics.cpp
> +		if (obb1 != m_CollisionEntities.at(i)->GetComponent<component::BoundingBoxComponent>()->GetOBB())
You could probably use a std::map here to avoid looping through all collision entities.

2020-10-01 13:16 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +void component::MeleeComponent::Update(double dt)
More comments plez

2020-10-01 13:17 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +	m_AttackIntervall = intervall;
Interval is spelled with one L in english, two in swedish ;)

2020-10-01 13:20 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +	if (list.size() != 0)
This "if" is unneccessary. Since if the size is 0 the for loop will not run anyway.

2020-10-01 13:21 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +		for (int i = 0; i < list.size(); i++)
You should use unsigned int wherever possible for consistency and clarity

2020-10-01 13:23 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +
Unneccesary empty line

2020-10-01 13:25 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +	unsigned int indices[36] = {};
This is probably a fair place for hardcoding, but put a comment that explains more clearly what you're doing.

2020-10-01 13:26 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.cpp
> +	indices[33] = 2; indices[34] = 6; indices[35] = 7;
This is probably a fair place for hardcoding, but put a comment that explains what you are doing.

2020-10-01 13:38 UTC, Whixx submitted a review, later dismissed
Made some comments, look at those.

2020-10-02 13:24 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.h
> +		//std::vector<Entity*> collideList;
?

2020-10-02 13:25 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/MeleeComponent.h
> +		//void RenderUpdate(double dt);
?

2020-10-02 13:25 UTC, Whixx commented on StortSpelProjekt/Game/src/Gamefiles/Components/PlayerInputComponent.cpp
> +		//Log::Print("Left Mouse button down \n");
Delete unneccesary code. Unless there is a purpose for it

2020-10-02 13:26 UTC, Whixx requested changes
Look at my comments

2020-10-02 13:39 UTC, Whixx approved these changes
Noice

2020-10-02 13:43 UTC, Anteanten approved these changes

2020-10-02 13:44 UTC, merged