Dash
jocke1995/StortSpelProjekt pull request #91
Opened 2020-10-05 12:17 UTC by LeoWikstrom

2020-10-05 13:39 UTC, jakkeez commented on StortSpelProjekt/Game/src/Gamefiles/Components/PlayerInputComponent.cpp
> +	}
Wouldn't use of dt work as well, instead of external library?

2020-10-05 13:40 UTC, jakkeez reviewed
Comment (Or question rather) about implementation, will probably approve if comment is solved (i.e answered)

2020-10-06 13:48 UTC, jocke1995 commented on StortSpelProjekt/Engine/src/ECS/Components/Collision/CapsuleCollisionComponent.cpp
> +	return dynamic_cast<btCapsuleShape*>(m_pShape)->getHalfHeight() + dynamic_cast<btCapsuleShape*>(m_pShape)->getRadius();
use static_cast, wrong usage of dynamic_cast

2020-10-06 13:50 UTC, jocke1995 commented on StortSpelProjekt/Vendor/config.txt
> +i_windowHeight 432
Dont forget to change it back to 1920, 1080 when you merge

2020-10-06 13:52 UTC, jocke1995 requested changes, later dismissed
Found two bugs when testing the dash:
1. Sometimes dashing out of the scene (tried several times and it doesn't happen everytime, so it might be hard to debug)
2. Dashing sideways (holding "w" and then double-tapping "a" or "d") sometimes dashes the wrong direction.

2020-10-07 12:04 UTC, jakkeez approved these changes, later dismissed
Minor fix is that in input I would be nice to utilize our implemented timer chronos instead of creating a new one. Nothing major, just a small fix that should be noted but can be fixed at a later point.

2020-10-07 12:13 UTC, jocke1995 approved these changes, later dismissed
Bra.

2020-10-07 12:20 UTC, jakkeez approved these changes

2020-10-07 12:21 UTC, jocke1995 approved these changes

2020-10-07 12:21 UTC, merged