Connect by console
jocke1995/StortSpelProjekt pull request #94
Opened 2020-10-05 13:29 UTC by Anteanten

This features allows players to connect to the server by writing connect:[IP]
I also fixed so other players moves smoothly and have collision

To test this you need to start server.exe in the bin folder; write "1" followed by "AddClient" twice to add 2 slots. Then open up two instances of either sandbox or game. Using the console write "connect:localhost" on both instances and you will see another cube that is controlled by the other instance.

OBS! if you open up from the exe in bin. make sure to build it from VS first and move everything inside it to the corresponding folder by sln. the pathing to many files is not setup for /bin/****

2020-10-06 09:18 UTC, LeoWikstrom requested changes
Looks sexy, just a few things to fix. Game works fine, but when running Sandbox the clients do not send any packets. Maybe look into that as well?

2020-10-06 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/ImGUI/ImGuiHandler.cpp
> +    else if (Stricmp(command.c_str(), "CONNECT") == 0)
Would be good to have a check if i_network in config is set to 1. If it is set to 0, the program crashes when typing the command

2020-10-06 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/ImGUI/ImGuiHandler.cpp
> +            EventBus::GetInstance().Publish(&ConnectToServer(arguments.at(0).c_str()));
A default would be nice, though not required. If there is no argument, arguments[0] is -1. In this case it could perhaps be good to instead use s_ip from the config file?

2020-10-06 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/ImGUI/ImGuiHandler.cpp
> +    m_Commands.push_back("CONNECT");
Also here the check for i_network could be good, to keep the command from showing up in HELP and autocomplete when there is no network

2020-10-06 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Engine/src/Network/Network.cpp
> +        ImGuiHandler::GetInstance().AddLog("Connection to %s failed", ip.c_str());
After I connected successfully, I tried connecting to a random IP which of course failed. When I then tried to again connect to the correct IP, this message was printed, while the server said that I had been connected. However, no packets were sent. Is this expected behaviour?

2020-10-06 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/main.cpp
> +            if (networkTimer >= networkUpdateRate) {
Block should start on a new line, as per the code standard

2020-10-06 09:18 UTC, LeoWikstrom commented on StortSpelProjekt/Game/src/main.cpp
> +    for (int i = 0; i < 5; i++)
I love it

2020-10-06 10:46 UTC, LeoWikstrom approved these changes, later dismissed

2020-10-07 09:55 UTC, jakkeez submitted a review, later dismissed

2020-10-07 10:05 UTC, jakkeez approved these changes

2020-10-07 11:12 UTC, LeoWikstrom approved these changes

2020-10-07 11:12 UTC, merged