Added connection logging in console on server-side and imgui client-side
jocke1995/StortSpelProjekt pull request #96
Opened 2020-10-07 11:22 UTC by jakkeez

New logging on server-side in console and imgui on client-side when sending and receiving packages. Added a new debug flag as well to prevent this logging to clutter imgui and console if they are not interesting at the current time.

2020-10-07 12:24 UTC, Anteanten requested changes, later dismissed

2020-10-07 12:24 UTC, Anteanten commented on StortSpelProjekt/Server/src/ClientPool.cpp
> -		m_ConsoleString.append("Recieved a packet from client " + std::to_string(socket) + "; " + std::to_string(packet.getDataSize()) + " BYTES\n");
This should not be removed

2020-10-08 07:04 UTC, Anteanten approved these changes

2020-10-08 08:28 UTC, LeoWikstrom approved these changes
Everything seems to work

2020-10-08 08:28 UTC, merged